---
- name: Tag the hostname and ansible_groups
  ec2_tag:
    region: "{{aws_region}}"
    resource: "{{ansible_ec2_instance_id}}"
    state: present
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    tags: { "Name":"{{hostname}}", "ansible_groups":"{{group_names|join(',')}}" }

- name: Tag the Service
  ec2_tag:
    region: "{{aws_region}}"
    resource: "{{ansible_ec2_instance_id}}"
    state: present
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    tags: { "Service":"Tools" }
  when: '"admin-tools" in group_names'

- name: Tag the Service
  ec2_tag:
    region: "{{aws_region}}"
    resource: "{{ansible_ec2_instance_id}}"
    state: present
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    tags: { "Service":"Web Server" }
  when: '"web-server" in group_names'

#- name: list the volumes for the instance
#  ec2_vol:
#    instance: "{{ansible_ec2_instance_id}}"
#    region: "{{aws_region}}"
#    state: list
#    aws_access_key: "{{aws_access_key}}"
#    aws_secret_key: "{{aws_secret_key}}"
#  with_items: ec2.tagged_instances
#  register: ec2_vol

#- name: Display list of volumes
#  debug: ec2_vol.stdout_lines

#- name: tag the volumes
#  ec2_tag:
#    region: "{{aws_region}}"
#    resource: "{{items}}"
#    state: present
#    aws_access_key: "{{aws_access_key}}"
#    aws_secret_key: "{{aws_secret_key}}"
#    tags: { "Name":"{{hostname}}", "ansible_groups":"{{group_names|join(',')}}" }
#  with_subelements:
#    - ec2_vol.results
#    - volumes
