---
- name: Gather ec2 facts
  ec2_facts:
  when: dc_env == "aws"

- name: Set Host name
  hostname: name={{hostname}}

- name: Replace default hosts file
  template: src=hosts.j2 dest=/etc/hosts

- name: Prevent IP Spoofing
  template: src=hosts.conf dest=/etc/host.conf

- name: Update ec2 tags
  include: ec2-tags.yml
  when: dc_env == "aws"
