#
#About: This must be run on all new servers
#
---
- hosts: '{{inventory}}'
  sudo: yes
  roles:
  - common
  - hostname
  - ntp
  - motd
  - ssh-banner
#  - postfix
  - apache
  - fitbitsync
  #- psad
  #- rootkit-scanners
  #- tiger
