# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyncFitBit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitBitAuthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('expries_in', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('token_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=20)),
                ('height_unit', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=5)),
                ('weight_unit', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=25)),
                ('fitbit_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='FitBitData',
        ),
    ]
