---
- name: Install UFW
  apt: name={{item}} state=present
  with_items:
  - ufw

- name: Enable iptable logging for INPUT
  shell: sudo iptables -A {{item}} -j LOG
  with_items:
  - INPUT
  - FORWARD
  changed_when: False
