---
- name: Install misc packages
  apt: name={{item}} state=present
  with_items:
  - curl
  - git
  - zip
  - unzip
  - vim
  - logrotate
  - ufw
  - python-pip

- name: Install pip modules
  pip: name={{item}} state=present
  with_items:
  - boto
